### ISSUE TITLE
Not really an issue but an enhancement

### ISSUE THREAD

**Issue by hillschmidt** [cosmocode/dokuwiki-plugin-statdisplay#23]
The Table header line for daily averages and averages per hour is the same: both start in the header with DAY but should be HOUR for the 2nd table.

Very simple to improve (what I did in my Wiki pe.hillschmidt.de):
helper/table.php line 148 changed from
        $this->head($this->getLang('day'));
to
        $this->head($this->getLang($by));

and introduced in language file a new line for
$lang['hour']                  = 'Std';
 (for German)

It would be nice if this will be included in an update.
By the way, I'm running Binky ... for me perfect so that the Compatibility should be checked O.K. for the Plugin.

CU, Andreas

**Comment by micgro42** [comment]
This seems to be already fixed.
