### ISSUE TITLE
Traffic is overreported when media-files are big

### ISSUE THREAD

**Issue by haraldronge** [cosmocode/dokuwiki-plugin-statdisplay#24]
The numbers I see reported as traffic in MBytes are completely impossible.

On a site that's hardly contains 300 MBytes overall users are reported to cause traffic up to 10GBytes in a short time-frame.
This is probably caused by simply adding up entries like the one below, where a user only had downloaded a single file, but where multiple log entries have been generated for that.

212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:08:44 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/86-q24-arcadis_proposal_smart_sustainability_eindhoven_23012014.pdf HTTP/1.1" 200 678107 "working_groups/wg_users/proposals/proposal_86" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:08:45 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/86-q24-arcadis_proposal_smart_sustainability_eindhoven_23012014.pdf HTTP/1.1" 200 678107 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:86-q24-arcadis_proposal_smart_sustainability_eindhoven_23012014.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:08:45 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/86-q24-arcadis_proposal_smart_sustainability_eindhoven_23012014.pdf HTTP/1.1" 200 678107 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:86-q24-arcadis_proposal_smart_sustainability_eindhoven_23012014.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:10 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "working_groups/wg_users/proposals/proposal_199" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:10 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:10 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:11 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:11 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:11 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:12 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:12 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
212.189.110.21 - mariekeoosterbaan [17/Feb/2014:16:09:12 +0100] "GET /_media/working_groups/wg_users/proposals/illustrations/199-q24-6013_slim_verduurzamen_eindhoven.pdf HTTP/1.1" 200 6923981 "http://turtur.biz/share_proposals/lib/exe/fetch.php?media=working_groups:wg_users:proposals:illustrations:199-q24-6013_slim_verduurzamen_eindhoven.pdf" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
etc. etc. ............ goes on for some time

**Comment by splitbrain** [comment]
When the same file is logged multiple times, then it is counted multiple times. I don't see anything wrong with that.
