### ISSUE TITLE
Small logging issue

### ISSUE THREAD

**Issue by ajfre** [cosmocode/dokuwiki-plugin-statdisplay#29]
The request
"GET /doku.php?id= :euleninfos:eulenliteratur:eulenzeitschriften:eulenrundblick:eulenrundblick-39 HTTP/1.1"
gets logged in data/meta/access.log as
"GET startseite :euleninfos:eulenliteratur:eulenzeitschriften:eulenrundblick:eulenrundblick-39 HTTP/1.1"

(Seemed to be a bot, that requested "/doku.php?id= :euleninfos:..." with space following =)

**Comment by splitbrain** [comment]
This plugin does no logging
