### ISSUE TITLE
Stat Failed Apache Errors

### ISSUE THREAD

**Issue by benhartwich** [cosmocode/dokuwiki-plugin-statdisplay#31]
Hi,

I´ve got apache errors everytime somebody visits one site: PHP Warning:  filesize(): stat failed for access.log in /dokuwiki/lib/plugins/statdisplay/helper/log.php on line 53

Release 2014-05-05a "Ponder Stibbons"

What can I do?

**Comment by micgro42** [comment]
This probably means that the path to your logfile is wrong. Check your configuration.
