### ISSUE TITLE
Traffic by User incorrect

### ISSUE THREAD

**Issue by LGeyer** [cosmocode/dokuwiki-plugin-statdisplay#37]
As the values on our wiki did not change during the last two month I assume, that not the traffic of the last 7 days is shown, but the traffic of the last 7 days with traffic.
(Most changes are done by the admin - and his traffic is not counted.)

**Comment by micgro42** [comment]
This is most likely a symptom  of the same problem as #34 .

**Comment by micgro42** [comment]
Please update the plugin to today's new version and see if the problem still occurs.
