### ISSUE TITLE
Non-breaking space in tables are escaped after upgrade to "Elenor of Tsort"

### ISSUE THREAD

**Issue by mihula** [cosmocode/dokuwiki-plugin-statdisplay#45]
Plugin is using non-breaking space html entity (`&#xa0;`) for displaying size (eg. 95 MB). In latest release (2016-06-26 "Elenor of Tsort") those entities are escaped in tables therefore displayed as is (eg. `95&#xa0;MB`).

**Comment by micgro42** [comment]
This has been fixed in the first hotfix to the release: https://github.com/splitbrain/dokuwiki/releases/tag/release_stable_2016-06-26a
